### ISSUE TITLE
:lady_beetle: Fix: Refresh invitation

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/back-unicloud#140]
rota ` /update-invitation/` está criando convites expirados
- convites ficam pendentes ad eternum

**Comment by joaolavelino** [comment]
na hora de criar convites eles já são criados como expirados



![Image](https://user-images.githubusercontent.com/84484002/187707361-b3ef1eb0-d2b9-4b37-a4ea-1ba57856f04d.png)
