### ISSUE TITLE
✨ CALC SETTINGS - SUBSCRIPTION

### ISSUE THREAD

**Issue by joaolavelino** [uni-clouds/back-unicloud#161]
# Tela de gerenciamento de subscriptions

![Image](https://user-images.githubusercontent.com/84484002/188158260-63ac74bf-757f-4f88-a732-e294f9b0178d.png)

# Chamadas para o back

### - Formato das subscriptions:
`{  name: string  ,  months: integer  ,  discount:  float  ,   id:  integer  }`

### - Create Subscriptions:
A gente tinha falado em deixar o usuário colocar uma porcentagem em números inteiros, para depois dividirmos por 100 na hora de salvar no back, para facilitar os cálculos dos valores.
Exemplo de dado que vou mandar:
`{  name: "Four years"  ,  months: 48  ,  discount:  0.35*  }`
_*o campo pede em porcentagem e permite números inteiros. Você prefere que eu mande o inteiro ou já mande em decimal?_

###  - Retrieve subscriptions:
Receber um array das subscriptions existentes, no formato ali que coloquei acima:

### - Update subscriptions:
Vou mandar um objeto (name, months, discount)  com as alterações, não permito enviar se  nenhuma alteração tiver sido feita.
 - Questão de propriedades únicas: Estou apenas considerando os nomes dos planos de subscription como propriedade única. 

### - Delete:
Eu vou mandar o id da subscription.

--

## - Endpoints
Preciso saber os endpoints de cada chamada

-------

# Erros
Seria legal eu saber quais são os erros possíveis que sao implementados no back, para eu fazer o tratamento no front.

**Comment by fegma59** [comment]
Dados do back-end

`POST http://127.0.0.1:8000/root/subscriptions/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "name": "One-Year",
    "months": 12,
    "discount": 25
}
###

GET http://127.0.0.1:8000/root/subscriptions/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
}
###

PATCH http://127.0.0.1:8000/root/subscriptions/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "new_name": "Three-Year-Subs",
    "subscription_id": 2,
    "new_months_value": 36,
    "new_discount_value": 70
}

###
DELETE http://127.0.0.1:8000/root/subscriptions/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "subscription_id": 1
}`

**Comment by fegma59** [comment]
Feito na branch e card dos Ratios.
