### ISSUE TITLE
🐞 SUBSCRIPTIONS - Rota não acessível

### ISSUE THREAD

**Issue by joaolavelino** [uni-clouds/back-unicloud#163]
![Image](https://user-images.githubusercontent.com/84484002/188209409-d02a38aa-9a52-461b-9f92-fb7fc60f22a7.png)

Como não estava conseguindo fazer as chamadas dos subscriptions. Testei abrir direto na página do back, mas também não esta disponível, retornando status 500.

https://unicloud-back-development.azurewebsites.net/root/subscriptions/

**Comment by fegma59** [comment]
Faltava rodar as migrações de banco de dados no back de dev.
