### ISSUE TITLE
🐞 BUG: Patch Opportunity status

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/back-unicloud#83]
A rota /opportunity-register/ não está aceitando o método PATCH
**retorna status 405 'not allowed'**

**Comment by fegma59** [comment]
@ManuCoutinho a rota correta para o root atualizar o status de uma oportunidade via patch é:

 /opportunity-status/

**Comment by ManuCoutinho** [comment]
@fegma59 funcionou com root/opportunity-status/
Pode ficar asim?

**Comment by fegma59** [comment]
É isso mesmo!
