### ISSUE TITLE
🐞 FIX: /menu/

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/back-unicloud#92]
@fegma59  a rota /menu/ não está devolvendo o item 'resources'

![Image](https://user-images.githubusercontent.com/80268705/181809530-f584b44b-ddef-4c43-b1f6-937eb5938ffa.png)

**Comment by fegma59** [comment]
Olá @ManuCoutinho. 

Veja a issue original, no objeto que voce me enviou, não tinha este item:
https://github.com/uni-clouds/back-unicloud/issues/86


Estou acrescentando este item para o Root, confirme se não tem mais nada faltando e crie um novo card caso tenha.

**Comment by fegma59** [comment]
Me envie o objeto, não sei qual é o icon, rota e etc.

Nessa estrutura de menu, como que está funcionando o sistema de tradução?
Não deveria ser variáveis?

**Comment by ManuCoutinho** [comment]
@fegma59 Oh sorry!
Seguem os dados para inclusão:
{
"icon": "clarity:resource-pool-outline-badged",
"text": "Recursos",
"link": "/resources"
},
